name: Build DeliveryOCR exe

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytesseract pillow openpyxl pyinstaller
    - name: Download Tesseract OCR installer
      run: |
        Invoke-WebRequest -Uri https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.3.1.20230401.exe -OutFile tesseract-setup.exe
    - name: Install Tesseract OCR
      run: |
        Start-Process -Wait -FilePath .\\tesseract-setup.exe -ArgumentList '/S'
    - name: Build exe with PyInstaller
      run: |
        pyinstaller --onefile DeliveryOCR.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeliveryOCR-exe
        path: dist\\DeliveryOCR.exe
